### ISSUE TITLE
BinaryStream

### ISSUE THREAD

**Issue by charliegustard** [Zzm317/ZMusicBox#27] opened 2017-10-22 12:28 UTC
[22:58:37] [Server thread/CRITICAL]: Could not execute task ZMusicBox\MusicPlayer: Argument 1 passed to pocketmine\utils\BinaryStream::putVarInt() must be of the type integer, null given, called in phar://C:/Users/Admin/Creative Cloud Files/Desktop/MusicalChairsServer/MusicalChairs - DEV/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/BlockEventPacket.php on line 53
[22:58:37] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putVarInt() must be of the type integer, null given, called in phar://C:/Users/Admin/Creative Cloud Files/Desktop/MusicalChairsServer/MusicalChairs - DEV/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/BlockEventPacket.php on line 53" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 335
[22:58:37] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/BlockEventPacket(53): pocketmine\utils\BinaryStream->putVarInt(NULL )
[22:58:37] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(99): pocketmine\network\mcpe\protocol\BlockEventPacket->encodePayload()
[22:58:37] [Server thread/DEBUG]: #2 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
[22:58:37] [Server thread/DEBUG]: #3 src/pocketmine/Player(3066): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\BlockEventPacket object, boolean , boolean )
[22:58:37] [Server thread/DEBUG]: #4 src/pocketmine/Player(3086): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\BlockEventPacket object, boolean , boolean )
[22:58:37] [Server thread/DEBUG]: #5 ZMusicBox-master/src/ZMusicBox/ZMusicBox(199): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\BlockEventPacket object)
[22:58:37] [Server thread/DEBUG]: #6 ZMusicBox-master/src/ZMusicBox/ZMusicBox(240): ZMusicBox\ZMusicBox->Play(integer 14, integer 4, integer 0)
[22:58:37] [Server thread/DEBUG]: #7 src/pocketmine/scheduler/TaskHandler(160): ZMusicBox\MusicPlayer->onRun(integer 6079)
[22:58:37] [Server thread/DEBUG]: #8 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 6079)
[22:58:37] [Server thread/DEBUG]: #9 src/pocketmine/Server(2506): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 6079)
[22:58:37] [Server thread/DEBUG]: #10 src/pocketmine/Server(2253): pocketmine\Server->tick()
[22:58:37] [Server thread/DEBUG]: #11 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[22:58:37] [Server thread/DEBUG]: #12 src/pocketmine/Server(1714): pocketmine\Server->start()
[22:58:37] [Server thread/DEBUG]: #13 src/pocketmine/PocketMine(558): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Users/Admin/Creative Cloud Files/Desktop/MusicalChairsServer/MusicalChairs - DEV/PocketMine-MP.phar/, string C:\Users\Admin\Creative Cloud Files\Desktop\MusicalChairsServer\MusicalChairs - DEV\, string C:\Users\Admin\Creative Cloud Files\Desktop\MusicalChairsServer\MusicalChairs - DEV\plugins\)
[22:58:37] [Server thread/DEBUG]: #14 C:/Users/Admin/Creative Cloud Files/Desktop/MusicalChairsServer/MusicalChairs - DEV/PocketMine-MP.phar(1): require(string phar://C:/Users/Admin/Creative Cloud Files/Desktop/MusicalChairsServer/MusicalChairs - DEV/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by TheRoyalBlock** [comment] 2017-10-22 12:49
I'll take a look at this, I think it's just some minor Api updates

**Comment by TheRoyalBlock** [comment] 2018-01-03 21:21
Yeah, I can't reproduce this. For now, I'll close this until I can get confirmation from somebody else.

**Comment by TheRoyalBlock** [comment] 2018-01-15 18:11
Sorry bout that, I'm now able to reproduce it. I'll work on fixing this and push changes soon.

**Closed** 2018-01-15 19:38 UTC
Labels: bug, duplicate
